
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 111519 bytes/channel
 *	Total Size: 1 * 111519 + 4 (header) = 111563 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/ABUNAI/Documents/Gatech/CS/2261/JeffreyBaucom_FinalProject/gameSong.wav
 *	Time-stamp: Tue Nov 10 23:00:42 2015
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 111519

extern const unsigned char gameSong[111519];

#endif /* __GAMESONGH__ */
