
/**************************************************************
 *	
 *	shootSFX, 8 bit, 11025Hz,
 *	1 channel, 3070 bytes/channel
 *	Total Size: 1 * 3070 + 4 (header) = 3114 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/ABUNAI/Documents/Gatech/CS/2261/JeffreyBaucom_FinalProject/shootSFX.wav
 *	Time-stamp: Tue Nov 10 23:01:06 2015
 *	
 **************************************************************/

#ifndef __SHOOTSFXH__
#define __SHOOTSFXH__

#define SHOOTSFXFREQ 11025
#define SHOOTSFXLEN 3070

extern const unsigned char shootSFX[3070];

#endif /* __SHOOTSFXH__ */
